Create CI.yml
wafflestudio/interactive-web-server pull request #4
Opened 2022-04-01 06:15 UTC by padme0421

2022-04-24 13:01 UTC, Gorani9 requested changes
CI/CD 구축하느라 많이 고생하셨습니다!
코드보면서 저도 많이 배운 것 같습니다
제가 코멘트 남긴 부분들만 바꾸면 머지해도 좋을 것 같습니다

2022-04-24 13:01 UTC, Goraniieee commented on .github/workflows/CI.yml
> +      DB_PASSWORD: root
실제 DB에 맞게 수정만 하시면 될 듯합니다

2022-04-24 13:01 UTC, Goraniieee commented on .github/workflows/CI.yml
> +        mysql -h 127.0.0.1 -uroot -proot -e "SHOW DATABASES"
마찬가지로 이 부분 빼시거나 실제 RDS 연결확인으로 교체하면될 것 같네요!

2022-04-25 15:22 UTC, padme0421 commented on .github/workflows/CI.yml
> +      DB_PASSWORD: root
다시 생각해보니 이 부분이 CI만을 위해 테스트용 db에 대한 연결을 테스트하는 거라서 실제 db로 하는 것보다 이렇게 두는 게 나을 것 같습니다. 이대로 해도 괜찬을까요?

2022-04-25 15:23 UTC, padme0421 commented on .github/workflows/CI.yml
> +        mysql -h 127.0.0.1 -uroot -proot -e "SHOW DATABASES"
여기도 마찬가지로 테스트용 db 연결 확인하는 부분입니다

2022-04-25 16:40 UTC, Gorani9 commented on .github/workflows/CI.yml
> +      DB_PASSWORD: root
아......!! 그렇군요

2022-04-25 16:41 UTC, Gorani9 approved these changes

2022-05-04 08:57 UTC, merged